name: Java CI with Maven and SonarQube

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: maven

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: SonarQube Scanner
        run: mvn sonar:sonar -Dsonar.projectKey=<your-project-key> -Dsonar.organization=<your-organization-key> -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=${{ secrets.SONARQUBE_TOKEN }}
